# Generated by Django 2.1.4 on 2018-12-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20181223_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='observacaoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
