# Generated by Django 2.1.4 on 2018-12-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_auto_20181223_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='observacaoes',
            new_name='observacoes',
        ),
    ]
